sys-apps/nix: add missing boehm-gc[cxx] depend (thanks to wiselord)
Build failed as:
  CXX    src/libexpr/eval.o
    src/libexpr/eval.cc:18:23: fatal error: [m[Kgc/gc_cpp.h: No such file or directory
    compilation terminated.

Package-Manager: Portage-2.3.3, Repoman-2.3.1