dev-haskell/gtk2hs-buildtools: fix build against alex-3.1.6 (by Gooberpatrol66)
New alex does not generate 'ord' import
but lexer actions use it. Leads to a build error:

    c2hs/c/CLexer.x:400:49:
        Not in scope: ‘ord’

Added import for a missing 'ord'.

Bug: https://github.com/gentoo-haskell/gentoo-haskell/issues/465

Package-Manager: portage-2.2.26