dev-lang/ghc: ignore user's CFLAGS in cross-build mode (reported by leat)
Fallback to default CFLAGS as we don't yet propagate
target-based CFLAGS properly. GHC's build system
does support the ability but it will require a bit
more thought. Ignore user's chaice for cross-build case
for now.

Build breakage example:
    CBUILD=x86_64-pc-linux-gnu
    CHOST=armv7a-hardfloat-linux-gnueabi
    CTARGET=armv7a-hardfloat-linux-gnueabi

    CFLAGS="-O2 -pipe -march=armv7-a"

  Linking utils/ghc-cabal/dist/build/tmp/ghc-cabal ...

  /usr/armv7a-hardfloat-linux-gnueabi/tmp/portage/dev-lang/ghc-8.2.1_rc1/temp/ghc2232_0/ghc_563.c:1:0: error:
     error: bad value (armv7-a) for -march= switch
     #include "Rts.h"
     ^

Package-Manager: Portage-2.3.5, Repoman-2.3.2