haddock-2.5.x (ghc-6.12): actually requires ghc 6.12 Or it'll die with [26 of 27] Compiling Haddock.Backends.Html   ( src/Haddock/Backends/Html.hs, dist/build/haddock/haddock-tmp /Haddock/Backends/Html.o )
src/Haddock/Backends/Html.hs:1603:23:
    Not in scope: data constructor `HsSpliceTyOut'