Revert "dev-haskell/haskell-gi-base: bump up to 0.20.3"
This reverts commit 46b1740f29a11992e80ccff0443ed4ead8871fb5.

To revert API breake visible gi-gtk-hs-0.3.4.2 on:
  Preprocessing library gi-gtk-hs-0.3.4.2...
  [1 of 9] Compiling Data.GI.Gtk.ModelView.Types ( src/Data/GI/Gtk/ModelView/Types.hs, dist/build/Data/GI/Gtk/ModelView/Types.o )
  [2 of 9] Compiling Data.GI.Gtk.ModelView.TreeModel ( src/Data/GI/Gtk/ModelView/TreeModel.hs, dist/build/Data/GI/Gtk/ModelView/TreeModel.o )
  [3 of 9] Compiling Data.GI.Gtk.ModelView.CustomStore ( src/Data/GI/Gtk/ModelView/CustomStore.hs, dist/build/Data/GI/Gtk/ModelView/CustomStore.o )

  src/Data/GI/Gtk/ModelView/CustomStore.hs:345:28: error:
      • Couldn't match type ‘Bool’ with ‘Maybe GHC.Stack.Types.CallStack’
        Expected type: IORef (Maybe GHC.Stack.Types.CallStack)
          Actual type: IORef Bool
      • In the second argument of ‘ManagedPtr’, namely ‘isOwned’
        In the second argument of ‘($)’, namely ‘ManagedPtr fPtr isOwned’
        In a stmt of a 'do' block: return $ ManagedPtr fPtr isOwned