dev-haskell/serialise: restrict tests
Tests fails due to overlapping instances for Arbitrary due to the
addition of Vector instances in quickcheck-instances-0.3.32.

Error below:

tests/Tests/Serialise.hs:283:9: error:
    • Overlapping instances for Arbitrary (Vector.Primitive.Vector Int)
        arising from a use of ‘mkTest’
      Matching instances:
        instance (Vector.Primitive.Prim a, Arbitrary a) =>
                 Arbitrary (Vector.Primitive.Vector a)
          -- Defined in ‘Test.QuickCheck.Instances.Vector’
        instance (Vector.Primitive.Prim a, Arbitrary a) =>
                 Arbitrary (Vector.Primitive.Vector a)
          -- Defined at tests/Tests/Orphanage.hs:198:10
    • In the expression: mkTest (T :: T (Vector.Primitive.Vector Int))
      In the second argument of ‘testGroup’, namely
        ‘[mkTest (T :: T ()), mkTest (T :: T Bool), mkTest (T :: T Int),
          mkTest (T :: T Int8), ....]’
      In the expression:
        testGroup
          "Simple instance invariants"
          [mkTest (T :: T ()), mkTest (T :: T Bool), mkTest (T :: T Int),
           mkTest (T :: T Int8), ....]
    |
283 |       , mkTest (T :: T (Vector.Primitive.Vector Int))

Signed-off-by: Jack Todaro <solpeth@posteo.org>