dev-haskell/blaze-colonnade: bump lower bound of blaze-html up to 0.9
blaze-html-0.8 does not define `Semigroup Attribute` instances:

  src/Text/Blaze/Colonnade.hs:272:40: error:
    • No instance for (Semigroup Attribute) arising from a use of ‘<>’
    • In the first argument of ‘Cell’, namely ‘(a1 <> a2)’
      In the expression: Cell (a1 <> a2) (c1 <> c2)
      In an equation for ‘<>’:
          (Cell a1 c1) <> (Cell a2 c2) = Cell (a1 <> a2) (c1 <> c2)

Bug: https://github.com/gentoo-haskell/gentoo-haskell/pull/743
Package-Manager: Portage-2.3.44, Repoman-2.3.10