dev-haskell/chronos: RESTRICT=test, module conflict
  src/Chronos.hs:257:1: error:
    Ambiguous module name ‘Data.Vector’:
      it was found in multiple packages:
      AC-Vector-Fancy-2.4.0 vector-0.12.0.3

Package-Manager: Portage-2.3.86, Repoman-2.3.20
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>